version: '3'
services:
  apache:
    image: httpd:latest
    container_name: my_apache_container
    ports:
      - "80:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    restart: always
  watcher:
    image: alpine:latest
    container_name: apache_watcher
    volumes:
      - ./reload_script.sh:/reload_script.sh
      - .:/website
    command: sh -c "apk add --no-cache inotify-tools && /reload_script.sh"
    restart: always
