pipeline:
  identifier: Build_karlkarl281995_dock_http_1712438917735
  name: Build dock-http
  orgIdentifier: default
  projectIdentifier: dockhttp1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1712431655753
        repoName: karlkarl281995/dock-http
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: docker compose up
                  spec:
                    shell: Sh
                    command: |
                      #!/bin/bash
                      set -e

                      # Navigate to the directory containing the Docker Compose file
                      cd /Users/karlvalcourt/workbench/dock-http

                      # Build and start the Docker containers defined in the Docker Compose file
                      docker-compose up -d
                  timeout: ""
                  type: Run
                  description: |
                    #!/bin/bash
                    set -e

                    # Navigate to the directory containing the Docker Compose file
                    cd /Users/karlvalcourt/workbench/dock-http

                    # Build and start the Docker containers defined in the Docker Compose file
                    docker-compose up -d
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
